name: Start when a merge happens 
on: [pull_request, workflow_dispatch]
env:
  MONGODB_USERNAME: ahmad
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Get code
       uses: actions/checkout@v3
     - name: print the variable 
       run: echo '$MONGODB_USERNAME'
     - name: Commit changes to main branch after merge
       uses: EndBug/add-and-commit@v9
     
  